Repository TEIC/Stylesheets, pull requests merged in 2025-01, with the labels that each got.

#716 first teeny step in addressing #705 — make Makefile more readable
  Makefile
Labels: target: build

#727 actually process `<constraintDecl>`
  Test/expected-results/test.isosch
  Test/expected-results/testdrama.compiled.xml
  Test2/expected-results/testPure1.rng
  odds/extract-isosch.xsl
  odds/odd2odd.xsl
  odds/odd2relax.xsl
  odds/teiodds.xsl
Labels: type: bug, priority: high, conversion: schematron

#715 Correct sorting of tei:biblStruct when multiple dates available (#712)
  html/html_core.xsl
  latex/latex_core.xsl
Labels: status: fixUntested

#724 output `@class` for an `<ab>` that has a `@type`
  html/html_core.xsl
Labels: conversion: html
