Repository TEIC/Stylesheets, pull requests merged in 2025-07, with the labels that each got.

#762 copy *:xsl children of //tei:constraintDecl[@scheme eq 'schematron'] …
  odds/teiodds.xsl
Labels: type: bug, conversion: schematron

#747 Update target link to TCW 27 for deprecation warnings
  common/common_tagdocs.xsl
Labels: status: Go

#710 fix #703: update link in README.md
  README.md
Labels: status: needsDiscussion
